font_family JetBrainsMono Nerd Font Mono
font_size 10

foreground #E6E6E6
background #0D0D0D

cursor #ADADAD
cursor_text_color #0D0D0D

selection_foreground #0D0D0D
selection_background #ADADAD

url_color #ADADAD

color0 #0D0D0D
color1 #666666
color2 #808080
color3 #999999
color4 #808080
color5 #999999
color6 #ADADAD
color7 #E6E6E6

color8 #404040
color9 #808080
color10 #999999
color11 #ADADAD
color12 #999999
color13 #ADADAD
color14 #E6E6E6
color15 #FFFFFF

background_opacity 0.95
window_padding_width 12
hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0.8

scrollback_lines 10000

url_style curly

tab_bar_edge bottom
tab_bar_style powerline

active_tab_foreground #0D0D0D
active_tab_background #ADADAD

inactive_tab_foreground #999999
inactive_tab_background #151515

mouse_hide_wait 3.0
confirm_os_window_close 0

