font_family      JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font Italic
bold_font        JetBrainsMono Nerd Font Bold
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 10

background_opacity 0.95
window_padding_width 12
hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0.8
cursor_trail 10
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 2

scrollback_lines 10000

url_style curly

tab_bar_edge bottom
tab_bar_style powerline

mouse_hide_wait 3.0
confirm_os_window_close 0

foreground            #a6a6a6
background            #080808
background_opacity    0.98

selection_foreground  #c4c4c4
selection_background  #1a1a1a

cursor                #c4c4c4
cursor_text_color     #080808

url_color             #8a8a8a
active_border_color   #1a1a1a
inactive_border_color #121212

# ───────── ANSI

# black / base
color0   #000000
color8   #3d3d3d

# red / danger
color1   #4a4a4a
color9   #686868

# green
color2   #5c5c5c
color10  #a6a6a6

# yellow / warning
color3   #666666
color11  #b0b0b0

# blue / highlight
color4   #707070
color12  #b8b8b8

# magenta / pink
color5   #7a7a7a
color13  #d0d0d0

# cyan
color6   #848484
color14  #c0c0c0

# white / fg
color7   #a6a6a6
color15  #e0e0e0
