font_family      JetBrainsMono Nerd Font
italic_font      JetBrainsMono Nerd Font Italic
bold_font        JetBrainsMono Nerd Font Bold
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 9

enable_audio_bell no
background_opacity 0.95
hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0.8
cursor_trail 10
cursor_trail_decay 0.1 0.5

scrollback_lines 10000

url_style curly

tab_bar_edge bottom
tab_bar_style powerline

mouse_hide_wait 3.0
confirm_os_window_close 0

