theme[main_bg]="#0D0D0D"
theme[main_fg]="#E6E6E6"
theme[title]="#FFFFFF"
theme[hi_fg]="#FFFFFF"
theme[selected_bg]="#303030"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#666666"
theme[graph_text]="#ADADAD"
theme[meter_bg]="#1F1F1F"
theme[proc_misc]="#ADADAD"

theme[cpu_box]="#404040"
theme[mem_box]="#404040"
theme[net_box]="#404040"
theme[proc_box]="#404040"

theme[div_line]="#303030"

theme[temp_start]="#999999"
theme[temp_mid]="#ADADAD"
theme[temp_end]="#FFFFFF"

theme[cpu_start]="#666666"
theme[cpu_mid]="#ADADAD"
theme[cpu_end]="#FFFFFF"

theme[free_start]="#666666"
theme[free_mid]="#999999"
theme[free_end]="#ADADAD"

theme[cached_start]="#666666"
theme[cached_mid]="#999999"
theme[cached_end]="#ADADAD"

theme[available_start]="#808080"
theme[available_mid]="#ADADAD"
theme[available_end]="#E6E6E6"

theme[used_start]="#808080"
theme[used_mid]="#ADADAD"
theme[used_end]="#FFFFFF"

theme[download_start]="#666666"
theme[download_mid]="#ADADAD"
theme[download_end]="#FFFFFF"

theme[upload_start]="#666666"
theme[upload_mid]="#ADADAD"
theme[upload_end]="#FFFFFF"

theme[process_start]="#666666"
theme[process_mid]="#ADADAD"
theme[process_end]="#FFFFFF"
